[front]
template = "index.html"
[back]
listenhost = "0.0.0.0"
listenport = 8000
domains = [ "dns.1433.eu.org","dns.bypass.eu.org"]
cname = "www.baidu.com"
[basicauth]
check = false
username = "yumu"
password = "yumusb"